spring.application.name=Portfolio_Website
personaldetail.name=Nimit Shah
personaldetail.developer=Java developer
personaldetail.email=nimitshah240@gmail.com
personaldetail.phone=+91 6353756701
personaldetail.location=Gujarat, India
personaldetail.linkedin=https://www.linkedin.com/in/nimit-shah-4623411b8/
personaldetail.instagram=https://www.instagram.com/_nimittt_3000_/
personaldetail.whatsapp=https://wa.me/6353756701
personaldetail.github=https://github.com/Nimitshah240/
personaldetail.aboutme=<p>A passionate  Developer with strong skills in core Java, Spring Boot, REST APIs, and SQL-based backend development. Experienced in building clean, efficient, and scalable applications with a focus on performance and maintainability.</p><p> I love solving real-world problems through code and enjoy working in agile teams to deliver practical, business-ready solutions. Always eager to learn and grow, I'm actively improving my skills in advanced Java and modern backend technologies.<br> Looking to collaborate with forward-thinking teams or clients? let's turn your vision into reality! </p>

# Below line use to connect to mysql db of Xampp
#spring.datasource.url= jdbc:mysql://localhost:3306/portfoliowebsite
#spring.datasource.username=root
##spring.datasource.password=9af43358a79457f8b6c7201cf0027e8206bc9c61
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Hosted DB Filess.io
spring.datasource.url=jdbc:mysql://k9tk8.h.filess.io:61002/portfoliowebsite_completeas
spring.datasource.username=portfoliowebsite_completeas
spring.datasource.password=9af43358a79457f8b6c7201cf0027e8206bc9c61
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.minimum-idle=1
#spring.datasource.hikari.idle-timeout=10000
#spring.datasource.hikari.max-lifetime=30000
#spring.datasource.hikari.connection-timeout=30000
##spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.datasource.hikari.pool-name=PortfolioPool
#logging.level.com.zaxxer.hikari=DEBUG
